#
# SPDX-License-Identifier: MIT
# Copyright (c) 2020 Tano Systems LLC. All rights reserved.
#
PR_append = ".3"

LICENSE = "GPLv2+"
LIC_FILES_CHKSUM = "file://Licenses/README;md5=30503fd321432fc713238f582193b78e"

UBOOT_GIT_URI = "git://git.ti.com/git/processor-sdk/processor-sdk-u-boot.git"
UBOOT_GIT_PROTOCOL = "https"
BRANCH = "processor-sdk-u-boot-2019.01"
SRCREV = "8b90adfb1630ed19959f89d39a5100573bca90fa"
