#!/bin/sh /etc/rc.common
# Copyright (C) 2008-2011 OpenWrt.org
# Copyright (C) 2022 Tano Systems LLC

START=60

USE_PROCD=1
PROG=/usr/sbin/zabbix_agentd
CONFIG=/etc/zabbix/zabbix_agentd.conf

ZBX_AGENTD_RUN="/var/run/zabbix"
ZBX_AGENTD_CONF="${ZBX_AGENTD_RUN}/zabbix_agentd.conf"

ZBX_UCI_CONFIG="zabbix_agentd"
ZBX_UCI_SECTION="general"

ZBX_USER="zabbix"
ZBX_GROUP="zabbix"

# Usage: append_if cfg uci_name output_name
# add a config line of the form "output_name <value>"
# if the "uci_name" was found.
# output_name defaults to uci_name if not specified.
conf_append_if() {
	local cfg="$1"
	local uci_name="$2"
	local out_name="$3"
	if [ -z "$out_name" ]; then
		out_name=$uci_name
	fi
	config_get val $cfg $uci_name
	if [ -n "$val" ]; then
		echo "$out_name=$val" >> ${ZBX_AGENTD_CONF}
	fi
}

start_service() {
	mkdir -p ${ZBX_AGENTD_RUN}
	chown ${ZBX_USER}:${ZBX_GROUP} ${ZBX_AGENTD_RUN}

	config_load "${ZBX_UCI_CONFIG}"

	rm -rf ${ZBX_AGENTD_CONF}
	conf_append_if ${ZBX_UCI_SECTION} PidFile
	conf_append_if ${ZBX_UCI_SECTION} LogType
	conf_append_if ${ZBX_UCI_SECTION} LogFile
	conf_append_if ${ZBX_UCI_SECTION} LogFileSize
	conf_append_if ${ZBX_UCI_SECTION} DebugLevel
	conf_append_if ${ZBX_UCI_SECTION} SourceIP
	conf_append_if ${ZBX_UCI_SECTION} AllowKey
	conf_append_if ${ZBX_UCI_SECTION} DenyKey
	conf_append_if ${ZBX_UCI_SECTION} LogRemoteCommands
	conf_append_if ${ZBX_UCI_SECTION} Server
	conf_append_if ${ZBX_UCI_SECTION} ListenPort
	conf_append_if ${ZBX_UCI_SECTION} ListenIP
	conf_append_if ${ZBX_UCI_SECTION} StartAgents
	conf_append_if ${ZBX_UCI_SECTION} ServerActive
	conf_append_if ${ZBX_UCI_SECTION} Hostname
	conf_append_if ${ZBX_UCI_SECTION} HostnameItem
	conf_append_if ${ZBX_UCI_SECTION} HostMetadata
	conf_append_if ${ZBX_UCI_SECTION} HostMetadataItem
	conf_append_if ${ZBX_UCI_SECTION} HostInterface
	conf_append_if ${ZBX_UCI_SECTION} HostInterfaceItem
	conf_append_if ${ZBX_UCI_SECTION} RefreshActiveChecks
	conf_append_if ${ZBX_UCI_SECTION} BufferSend
	conf_append_if ${ZBX_UCI_SECTION} BufferSize
	conf_append_if ${ZBX_UCI_SECTION} MaxLinesPerSecond

	procd_open_instance
	procd_set_param command ${PROG} -c ${ZBX_AGENTD_CONF} -f
	procd_set_param respawn
	procd_set_param stdout 1
	procd_set_param stderr 1
	procd_close_instance
}
