#!/bin/sh

FORMAT=${1:-plain}

LOG_FILE=$(uci -q get snmpd.general.log_file)
LOG_FILE_PATH=$(uci -q get snmpd.general.log_file_path)

if [ "${LOG_FILE}" != "1" -o -z "${LOG_FILE_PATH}" ]; then
	echo "Logging to file is not configured"
	exit 1
fi

if [ ! -x /usr/bin/syslog_fc ]; then
	echo "/usr/bin/syslog_fc not exists"
	exit 2
fi

case "$FORMAT" in
	json|csv)
		/usr/bin/syslog_fc -e "%M" -f ${FORMAT} ${LOG_FILE_PATH}
		;;

	*)
		cat ${LOG_FILE_PATH}
		;;
esac
