#!/bin/sh
# Copyright (C) 2019 Anton Kikin <a.kikin@tano-systems.com>

do_overlay_setup() {
	OVERLAY_PARTITION=`cat /proc/cmdline | sed -e 's/^.*overlay_partition=\([a-zA-Z0-9_-]*\).*$/\1/g'`

	if [ "$OVERLAY_PARTITION" != "" ]; then
		echo "$OVERLAY_PARTITION" > /tmp/overlay_partition
	else
		echo "rootfs_data" > /tmp/overlay_partition
	fi
}

boot_hook_add preinit_main do_overlay_setup
