# -*- coding: utf-8 -*-
#
# Configuration file for the Sphinx documentation builder.
#
# This file does only contain a selection of the most common options. For a
# full list see the documentation:
# http://www.sphinx-doc.org/en/master/config

# -- Path setup --------------------------------------------------------------

# If extensions (or modules to document with autodoc) are in another directory,
# add these directories to sys.path here. If the directory is relative to the
# documentation root, use os.path.abspath to make it absolute, like shown here.
#
import os
import sys

sys.path.insert(0, os.path.abspath('sphinx'))

# -- Project information -----------------------------------------------------

project = u'TanoWrt Embedded Linux Distibution'
copyright = u'2023, Tano Systems LLC'
author = u'Tano Systems LLC'

# The short version
version = u'master'

# The full version, including alpha/beta/rc tags
release = u'master'

# -- General configuration ---------------------------------------------------

# to load local extension from the folder 'sphinx'
# If your documentation needs a minimal Sphinx version, state it here.
#
# needs_sphinx = '1.0'

# Add any Sphinx extension module names here, as strings. They can be
# extensions coming with Sphinx (named 'sphinx.ext.*') or your custom
# ones.
extensions = [
	'sphinx.ext.autosectionlabel',
	'sphinx.ext.extlinks',
	'sphinx.ext.todo',
	'sphinx_rtd_theme',
	'sphinx_tabs.tabs',
	'sphinx.ext.intersphinx',
	'sphinxcontrib.mermaid',
	'sphinx_design',
	'yocto-vars',
]

#	'hoverxref.extension',

autosectionlabel_prefix_document = True
autosectionlabel_maxdepth = 10

# Add any paths that contain templates here, relative to this directory.
templates_path = ['sphinx-templates']

# The suffix(es) of source filenames.
# You can specify multiple suffix as a list of string:
#
# source_suffix = ['.rst', '.md']
source_suffix = '.rst'

# The master toctree document.
master_doc = 'index'

# The language for content autogenerated by Sphinx. Refer to documentation
# for a list of supported languages.
#
# This is also used if you do content translation via gettext catalogs.
# Usually you set "language" from the command line for these cases.
language = u'en'

# The name of the Pygments (syntax highlighting) style to use.
#pygments_style = 'sphinx'
pygments_style = 'stata-dark'

# -- Options for HTML output -------------------------------------------------

# The theme to use for HTML and HTML Help pages.  See the documentation for
# a list of builtin themes.
#
html_theme = "sphinx_rtd_theme"

# Theme options are theme-specific and customize the look and feel of a theme
# further.  For a list of options available for each theme, see the
# documentation.
#
html_theme_options = {
    'navigation_depth': 5,
}

# Add any paths that contain custom static files (such as style sheets) here,
# relative to this directory. They are copied after the builtin static files,
# so a file named "default.css" will overwrite the builtin "default.css".
html_static_path = [ 'sphinx-static' ]

html_css_files = [
    'theme_overrides.css',  # override wide tables in RTD theme
    'custom.css'
]

html_favicon = 'sphinx-static/favicon.png'

# Custom sidebar templates, must be a dictionary that maps document names
# to template names.
#
# The default sidebars (for documents that don't match any pattern) are
# defined by theme itself.  Builtin themes are using these templates by
# default: ``['localtoc.html', 'relations.html', 'sourcelink.html',
# 'searchbox.html']``.
#
# html_sidebars = {}

html_sidebars = { '**': [ 'globaltoc.html', 'relations.html', 'sourcelink.html', 'searchbox.html'] }

# -- Options for HTMLHelp output ---------------------------------------------

# Output file base name for HTML help builder.
htmlhelp_basename = 'TanoWrt'

# -- Options for LaTeX output ------------------------------------------------

latex_elements = {
    # The paper size ('letterpaper' or 'a4paper').
    #
    # 'papersize': 'letterpaper',

    # The font size ('10pt', '11pt' or '12pt').
    #
    # 'pointsize': '10pt',

    # Additional stuff for the LaTeX preamble.
    #
    # 'preamble': '',

    # Latex figure (float) alignment
    #
    # 'figure_align': 'htbp',
}

# Grouping the document tree into LaTeX files. List of tuples
# (source start file, target name, title,
#  author, documentclass [howto, manual, or own class]).
latex_documents = [
    (master_doc, 'tanowrt.tex', u'TanoWrt Embedded Linux Distribution',
     u'Tano Systems LLC', 'manual'),
]


# -- Options for manual page output ------------------------------------------

# One entry per manual page. List of tuples
# (source start file, name, description, authors, manual section).
man_pages = [
    (master_doc, 'tanowrt', u'TanoWrt Embedded Linux Distribution',
     [author], 1)
]


# -- Options for Texinfo output ----------------------------------------------

# Grouping the document tree into Texinfo files. List of tuples
# (source start file, target name, title, author,
#  dir menu entry, description, category)
texinfo_documents = [
    (master_doc, 'tanowrt', u'TanoWrt Embedded Linux Distribution',
     author, 'tanowrt', 'TanoWrt Embedded Linux Distribution',
     'Miscellaneous'),
]


# -- Options for Epub output -------------------------------------------------

# Bibliographic Dublin Core info.
epub_title = project

# The unique identifier of the text. This can be a ISBN number
# or the project homepage.
#
# epub_identifier = ''

# A unique identification for the text.
#
# epub_uid = ''

# A list of files that should not be packed into the epub file.
epub_exclude_files = ['search.html']

# -- Extension configuration -------------------------------------------------

# -- Options for todo extension ----------------------------------------------

# If true, `todo` and `todoList` produce output, else they produce nothing.
todo_include_todos = True

smartquotes = True
numfig = True

# Remove the trailing 'dot' in section numbers
html_secnumber_suffix = " "

# inside conf.py
latex_engine = 'xelatex'
latex_elements = {
    'fontpkg': r'''
\setmainfont{DejaVu Serif}
\setsansfont{DejaVu Sans}
\setmonofont{DejaVu Sans Mono}
''',
    'preamble': r'''
\usepackage[titles]{tocloft}
\cftsetpnumwidth {1.25cm}\cftsetrmarg{1.5cm}
\setlength{\cftchapnumwidth}{0.75cm}
\setlength{\cftsecindent}{\cftchapnumwidth}
\setlength{\cftsecnumwidth}{1.25cm}
''',
    'fncychap': r'\usepackage[Bjornstrup]{fncychap}',
    'printindex': r'\footnotesize\raggedright\printindex',
}

latex_show_urls = 'footnote'

# Hide 'Created using Sphinx' text
html_show_sphinx = False

rst_prolog = """
.. include:: <s5defs.txt>
.. include:: <xhtml1-lat1.txt>
.. include:: <xhtml1-special.txt>

"""
##rst_prolog = """
##.. |project_name| replace:: %s
##.. |copyright| replace:: %s
##.. |author| replace:: %s
##""" % (project, copyright, author)

# Add 'Last updated' on each page ??????????
html_last_updated_fmt = '%d.%m.%Y'

# If false, no index is generated.
html_use_index = True

extlinks = {
    'tanowrt_github_blob': ('https://github.com/tano-systems/meta-tanowrt/blob/master%s', None),
}

# From https://stackoverflow.com/questions/32773139/how-can-i-configure-the-separator-character-used-for-menuselection
from docutils import nodes, utils
from sphinx.roles import _amp_re

def patched_menusel_role(typ, rawtext, text, lineno, inliner, options={}, content=[]):
    text = utils.unescape(text)
    if typ == 'menuselection':
        text = text.replace('-->', u'\N{RIGHTWARDS ARROW}')  # Here is the patch 
    spans = _amp_re.split(text)  

    node = nodes.emphasis(rawtext=rawtext)
    for i, span in enumerate(spans):
        span = span.replace('&&', '&')
        if i == 0:
            if len(span) > 0:
                textnode = nodes.Text(span)
                node += textnode
            continue
        accel_node = nodes.inline()
        letter_node = nodes.Text(span[0])
        accel_node += letter_node
        accel_node['classes'].append('accelerator')
        node += accel_node
        textnode = nodes.Text(span[1:])
        node += textnode

    node['classes'].append(typ)
    return [node], []

def setup(sphinx):
    import sys
    import os
    from docutils.parsers.rst import roles

    # Use 'patched_menusel_role' function for processing the 'menuselection' role
    roles.register_local_role("menuselection", patched_menusel_role)
