#!/bin/sh
#
# This shell script if placed in /etc/apcupsd
# will be called by /etc/apcupsd/apccontrol when apcupsd
# loses contact with the UPS (i.e. the serial connection is not responding).
# We send an email message to root to notify him.
#
HOSTNAME=`hostname`
MSG="$HOSTNAME Communications with UPS $1 lost"
#
(
   echo "Subject: $MSG"
   echo " "
   echo "$MSG"
   echo " "
   /usr/sbin/apcaccess status
) | $APCUPSD_MAIL -s "$MSG" $APCUPSD_MAIL_TO
exit 0
